Organization:
  category: Administrative
  links:
    partOf:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Organization
    researchStudy:
      # In FHIR a Practitioner is a stand alone resource, however in Gen3 all entities need a link
      targetProfile: http://hl7.org/fhir/StructureDefinition/ResearchStudy
      required: true


Practitioner:
  category: Administrative
  links:
    project:
      # link to "native" gen3 project
      targetProfile: project
      required: true


PractitionerRole:
  category: Administrative
  links:
    organization:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Organization
      required: true
    practitioner:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Practitioner
      required: true      


ResearchStudy:
  category: Administrative
  links:
    partOf:
      targetProfile: http://hl7.org/fhir/StructureDefinition/ResearchStudy
    principalInvestigator:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Practitioner
      required: true
    project:
      # link to "containing" project
      targetProfile: project
      required: true
  enums:
    focus.coding.code: http://hl7.org/fhir/ValueSet/condition-code


Patient:
  category: Administrative
  identifier: urn:ncpi:unique-string
  links:
    managingOrganization:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Organization
      required: true

ResearchSubject:
  category: Administrative
  submitter_id: urn:ncpi:unique-string
  links:
    study:
      targetProfile: http://hl7.org/fhir/StructureDefinition/ResearchStudy
      required: true
    individual:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Patient
      required: true


DocumentReference:
  category: data_file
  links:
    subject:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Patient
      required: true
  source: https://nih-ncpi.github.io/ncpi-fhir-ig/StructureDefinition-ncpi-drs-document-reference.json


SpecimenTask:
  category: Analysis
  subtype_of: Task
  links:
    input:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Specimen
      required: true
    output:
      targetProfile: http://hl7.org/fhir/StructureDefinition/DocumentReference
      required: true
  source: https://nih-ncpi.github.io/ncpi-fhir-ig/StructureDefinition-ncpi-specimen-task.json


Specimen:
  category: Biospecimen
  links:
    subject:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Patient
      required: true

Observation:
  category: Clinical
  links:
    subject:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Patient
      required: true
    specimen:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Specimen
    focus:
      targetProfile: http://hl7.org/fhir/StructureDefinition/ResearchStudy      
  enums:
    valueQuantity.code: http://hl7.org/fhir/ValueSet/ucum-common

Questionnaire:
  category: Clinical
  links:
    researchStudy:
      # In FHIR a Practitioner is a stand alone resource, however in Gen3 all entities need a link
      targetProfile: http://hl7.org/fhir/StructureDefinition/ResearchStudy
      required: true

QuestionnaireResponse:
  category: Clinical
  links:
    subject:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Patient
      required: true
    questionnaire:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Questionnaire
      required: true


FamilyRelationship:
  category: Administrative
  links:
    subject:
      targetProfile: http://hl7.org/fhir/StructureDefinition/Patient
      required: true  
  enums:
    code.coding.code: http://terminology.hl7.org/ValueSet/v3-FamilyMember
  constants:
    code.coding.code.value:
    - FA
  source: https://nih-ncpi.github.io/ncpi-fhir-ig/StructureDefinition-family-relationship.json

